name: Terraform
on:
  push:
    branches:
      - main
    pull_request:

jobs:
  terraform:
    name: Terraform
    runs-on: self-hosted
    env:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}

# keep this for later 
    defualts:
      run:
        working-directory: 07-managing-multiple-environments/file-structure/staging
      steps:
        - name: checkout
          uses: actions/checkout@v2

        - name: setup terraform
          uses: hashicorp/setup-terraform@v1
          with:
            terraform_version: 1.0.1
            # here a wrapper idk why 
          
        - name: formatiing file
          run: terraform fmt -check

        - name: initializing
          run: terraform initi

        - name: planning
          if : github.event_name== 'pull_request'
          run: terraform plan
          continue-on-error: true

        - name: applying
          run: terraform apply


