services:
  postgres_db:
    image: postgres:17
    container_name: postgres_db
    environment:
      - POSTGRES_USER=USER
      - POSTGRES_PASSWORD=PASS
      - POSTGRES_DB=DB
    ports:
      - "54432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U USER -d DB"]
      interval: 10s
      timeout: 5s
      retries: 3

  application:
    build: .
    container_name: application_container
    environment:
      - DB_CONN=Host=postgres_db;Port=5432;Database=DB;Username=USER;Password=PASS;
    ports:
      - "8080:8080"
    depends_on:
      postgres_db:
        condition: service_healthy

volumes:
  postgres_data:

  
