name: evaluation pipeline 
on:
  push:
    branches:
      - main
jobs:
  update-application:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: update on vm
        run: |
          docker compose up --build -d 
