name: evaluation pipeline part 2
on:
  pull_request:
    branches:
      - main
jobs:
  commenting-changed-files:
    runs-on: self-hosted
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: pull request
        id: show_changes
        run: |
         echo "comment=$(git diff main..HEAD)" >> "$GITHUB_OUTPUT"
         echo $comment

      - name: commenting
        run: |
          gh pr comment ${{ github.event.pull_request.number }} --body "changed files are ${{ steps.show_changes.outputs.comment }}"
          

        env:
          GH_TOKEN: ${{ github.token }}
 

        