name: evaluation pipeline part 2
on:
  pull_request:
    branches:
      - main
jobs:
  commenting-changed-files:
    runs-on: self-hosted
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: pull request
        id: show_changes
        run: |
         delim=EOF_$(openssl rand -hex 8)

         git fetch origin 
         COMMENT=$(git diff origin/main..HEAD)

         echo "comment<<$delim" >> $GITHUB_OUTPUT
         echo $COMMENT >> $GITHUB_OUTPUT
         echo "$delim" >> $GITHUB_OUTPUT

      - name: commenting
        # run: |
        #   gh pr comment ${{ github.event.pull_request.number }} --body 'Changed files are ${{ steps.show_changes.outputs.comment }}'
        # env:
        #   GH_TOKEN: ${{ github.token }}
        uses: peter-evans/create-or-update-comment@v2
        with:
          token: ${{ github.token }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Changed Files are
            ```diff 
            ${{ steps.show_changes.outputs.comment }}
            ```
