name: evaluation pipeline part 2
on:
  pull_request:
    branches:
      - main
jobs:
  commenting-changed-files:
    runs-on: self-hosted
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: pull request
        id: show_changes
        run: |
         git fetch origin 
         COMMENT=$(git diff origin/main..HEAD)
         echo "comment<<EOF" >> $GITHUB_OUTPUT
         echo $COMMENT >> $GITHUB_OUTPUT
         echo "EOF" >> $GITHUB_OUTPUT

      - name: commenting
        run: |
          COMMENT=$(cat << 'EOF'
          changed files are ${{ steps.show_changes.outputs.comment }}'
          EOF
          )
          gh pr comment ${{ github.event.pull_request.number }} --body $COMMENT
        env:
          GH_TOKEN: ${{ github.token }}
        